# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dustin/Documents/HellHeimRpg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dustin/Documents/HellHeimRpg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dustin/Documents/HellHeimRpg/CMakeFiles /home/dustin/Documents/HellHeimRpg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dustin/Documents/HellHeimRpg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HellHeim.exe

# Build rule for target.
HellHeim.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HellHeim.exe
.PHONY : HellHeim.exe

# fast build rule for target.
HellHeim.exe/fast:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/build
.PHONY : HellHeim.exe/fast

art.o: art.cpp.o

.PHONY : art.o

# target to build an object file
art.cpp.o:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/art.cpp.o
.PHONY : art.cpp.o

art.i: art.cpp.i

.PHONY : art.i

# target to preprocess a source file
art.cpp.i:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/art.cpp.i
.PHONY : art.cpp.i

art.s: art.cpp.s

.PHONY : art.s

# target to generate assembly for a file
art.cpp.s:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/art.cpp.s
.PHONY : art.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/game.cpp.s
.PHONY : game.cpp.s

graphics.o: graphics.cpp.o

.PHONY : graphics.o

# target to build an object file
graphics.cpp.o:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/graphics.cpp.o
.PHONY : graphics.cpp.o

graphics.i: graphics.cpp.i

.PHONY : graphics.i

# target to preprocess a source file
graphics.cpp.i:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/graphics.cpp.i
.PHONY : graphics.cpp.i

graphics.s: graphics.cpp.s

.PHONY : graphics.s

# target to generate assembly for a file
graphics.cpp.s:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/graphics.cpp.s
.PHONY : graphics.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/main.cpp.s
.PHONY : main.cpp.s

picker.o: picker.cpp.o

.PHONY : picker.o

# target to build an object file
picker.cpp.o:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/picker.cpp.o
.PHONY : picker.cpp.o

picker.i: picker.cpp.i

.PHONY : picker.i

# target to preprocess a source file
picker.cpp.i:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/picker.cpp.i
.PHONY : picker.cpp.i

picker.s: picker.cpp.s

.PHONY : picker.s

# target to generate assembly for a file
picker.cpp.s:
	$(MAKE) -f CMakeFiles/HellHeim.exe.dir/build.make CMakeFiles/HellHeim.exe.dir/picker.cpp.s
.PHONY : picker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... HellHeim.exe"
	@echo "... edit_cache"
	@echo "... art.o"
	@echo "... art.i"
	@echo "... art.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... graphics.o"
	@echo "... graphics.i"
	@echo "... graphics.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... picker.o"
	@echo "... picker.i"
	@echo "... picker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

